### ISSUE TITLE
Bronos doesn't start listening on 5005, and broker errors:

### ISSUE THREAD

**Issue by solarisfire** [jishi/bronos-client#4]
Git cloned the repository.
Did the npm install.
Did npm start.

Looks to start normally:

> bronos-client@0.0.3 start /home/solarisfire/bronos-client
> node index.js

2017-10-08T13:36:38.946Z INFO Token is 96de86591e117041848b7b2*********, now connecting to https://broker.bronos.net
2017-10-08T13:36:39.172Z INFO connected

Go to the browser on port 5010 and get a good response:

Your baseURL: https://broker.bronos.net/v1/96de86591e117041848b7b2*********

However navigating to the broker URL:

{"status":"error","message":"request to http://localhost:5005/ failed, reason: connect ECONNREFUSED 127.0.0.1:5005","stack":"Error\n    at ClientRequest.<anonymous> (/home/solarisfire/bronos-client/node_modules/node-fetch/index.js:133:11)\n    at emitOne (events.js:115:13)\n    at ClientRequest.emit (events.js:210:7)\n    at Socket.socketErrorListener (_http_client.js:401:9)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}

Can confirm Bronos is only listening on port 5010 and not 5005:

tcp        0      0 0.0.0.0:5010            0.0.0.0:*               LISTEN      1277/node

Using Ubuntu 16.04.
NPM version to help with debug:

{ 'bronos-client': '0.0.3',
  npm: '5.3.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.6.0',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.14.1',
  v8: '6.0.287.53',
  zlib: '1.2.11' }

**Comment by jishi** [comment]
If you install this manually (not the rpi image) you also need to run the
sonos-http-api on the same machine

https://github.com/jishi/node-sonos-http-api

**Comment by NovaGL** [comment]
You don't need to run it on the same machine
@jishi It should be a simple option to say where sonos-http-api is located

I changed mine and it works. Maybe it should gracefully fail with an easier to understand error.
