### ISSUE TITLE
Use Bronos for applications other than node-sonos-http-api

### ISSUE THREAD

**Issue by rkpatel33** [jishi/bronos-client#6]
I am wondering if I can easily user the client to hit endpoints on applications other than `node-sonos-http-api` running on my local network. Specifically I think this would be really useful to access my Raspberr Pi running Hassio, which is served up on `hassio.local:8123` which is just `192.168.7.34:8123` in my particular case.

Looking at the code, I think I can just set `BRONOS_SONOS_API_URL` to my Hassio IP address and the port setting to `8123` but I have not tried it yet.

Either way this concept is great and would happily pay a fee to keep the broker going.

**Comment by jishi** [comment]
Hi, yes in theory it would work, but it would only support GET requests and
query string parameters as of now (if I recall correctly). Feel free to use
it for that case for the time being, I'll let people know when I implement
a subscription model and request tracking. I'm gonna need it to avoid abuse
and be able to block I'll-behaving implementations.

**Comment by rkpatel33** [comment]
Great thanks. Btw, have you poster the broker sever code anywhere as well?  Curious to look at it. It would be great to be able to spin up a personal instance on AWS or something. Just thinking out loud...

____________
Rishi K. Patel

On Jun 19, 2018, at 11:58 AM, Jimmy Shimizu <notifications@github.com> wrote:

Hi, yes in theory it would work, but it would only support GET requests and
query string parameters as of now (if I recall correctly). Feel free to use
it for that case for the time being, I'll let people know when I implement
a subscription model and request tracking. I'm gonna need it to avoid abuse
and be able to block I'll-behaving implementations.

**Comment by rkpatel33** [comment]
Seems this ended up not working. The endpoint is returning HTML but seems the broker is expecting JSON:

```sh
# Bronos settings in .zshrc
export BRONOS_SONOS_API_URL=http://192.168.7.34:8123
export BRONOS_HTTP_PORT=8123
```

Response at `https://broker.bronos.net/v1/MYTOKEN/config/dashboard`:

```
{
"status": "error",
"message": "invalid json response body at http://192.168.7.34:8123/config/dashboard reason: Unexpected token < in JSON at position 0",
"stack": "FetchError: invalid json response body at http://192.168.7.34:8123/config/dashboard reason: Unexpected token < in JSON at position 0\n    at /Users/rishi/Projects/thirdparty/bronos-client/node_modules/node-fetch/lib/body.js:48:31\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"
}
```

Just passing on an update, I guess nothing really to do on your project. Thx.

**Comment by jishi** [comment]
Yeah, it was designed for a very specific purpose. The server code is not shared, because I intended it to implement payment stuff etc and I wasn't really interested in supporting people running their own server instance, also because it was never the intention to run anything yourself since the target was persons who couldn't figure this out themselves.

It's probably easier for you to setup dynamic DNS and letsencrypt certificates (for HTTPS) on your hassio device yourself :)

**Comment by rkpatel33** [comment]
Yes thank, that's my plan. There's an add on for it but I had a little trouble with it.
