### ISSUE TITLE
What is the default SSH login and password?

### ISSUE THREAD

**Issue by leenperjasknegt** [jishi/bronos-client#7]
First of all I love your sonos http project(s)!

Where can I find the SSH login and password? 
I installed the default image on a Raspberrypi 3 and would like to download some other mp3 clips to use with the clipall function. Is the default location still static/clips?

**Comment by jishi** [comment]
It's just root without a password. You may set a password if you like, but you need to invoke `lbu_commit` afterwards to persist the changes from the RAM-drive to the flash storage. 

Yes, the location is still the same. Not sure the exact full path. You can also reach it through samba share, so no need for SSH if that is more convenient. 

Are you doing a Halloween prank? It's actually really useful for just that :D

**Comment by leenperjasknegt** [comment]
Thank you for your response.

No its actually not for a Halloween prank but you give me some ideas ;)
I will use it to play a doorbell sound.

I changed the root password but how can I login via smb://? What credentials do I have to use?

**Comment by jishi** [comment]
It allow non-authenticated guest users, so you shouldn't need credentials.
Or it will be guest with no password.

**Comment by leenperjasknegt** [comment]
Ah ok, I just got it to work via SSH. But just tried to login anonymous via samba and it also works. Thank you! :)
