### ISSUE TITLE
Bronos returning errors

### ISSUE THREAD

**Issue by estiens** [jishi/bronos-client#8]
These days I mostly get 503 errors from the bronos site. Still maintained or should we find another solution?

**Comment by jishi** [comment]
I've had some users abusing the system by querying zones info or state
constantly, so I added some throttling parameters. The throttling should
not affect most normal use cases, but if you are suffering from it,
describe how and when you are receiving the 503.

If people need to sync state into a separate system, they should use the
webhook feature of the http api.

**Comment by estiens** [comment]
Hmmm, that's probably what's affecting me. I ping for state info about every 10 seconds (though I wouldn't nec call hitting an API every 10 seconds abuse, especially when rate limits weren't set). Wasn't aware the HTTP API had a webhook feature, will look into it! In the meantime will just hit my raspberry pi directly and bypass bronos. Only suggestion would be returning rate limit information in the API response (ie; "state endpoints are limited to 2 requests every 60 seconds, please reduce thenumber of your requests")
